### PR TITLE
[#32] improvement: Update to use simple catalog name

### PR DESCRIPTION
**Pull request by diqiu50**
Update the Trino connector playground to using simple catalog name

### CODE REVIEW

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Comment by qqqttt123** [comment]
Could you upgrade the version of Gravitino and trino?

**Comment by diqiu50** [comment]
> Could you upgrade the version of Gravitino and trino?

Ok

**Review by qqqttt123 — APPROVED** [review]
LGTM.

**Pull request merged**
